### ISSUE TITLE
Video: Node.js API [C02P03]

### ISSUE THREAD

**Issue by mixplick** [waldemarnt/node-typescript-api#8]
Olá pessoal,

Na configuração dos dados de `apiToken` e `appUrl`, estou recebendo esse erro abaixo, já procurei em outros lugares e não achei uma solução, aparentemente é algo relacionado ao `vscode + windows`, alguém mais com o mesmo problema?

`"Cannot parse config file: '"+fullFilename+"': SyntaxError: Unexpected token � in JSON at position 0"`

**Comment by waldemarnt** [comment]
@mixplick pode subir teu codigo em um repositório aqui no Github e me passar a URL pra eu testar?

**Comment by mixplick** [comment]
Olá @waldemarnt, obrigado pela disponibilidade em ajudar, [segue URL com o código]( https://github.com/mixplick/nodejs-api).

**Comment by waldemarnt** [comment]
@mixplick abri um pull request arrumando o problema, provavelmente foi o file encode do windows que colocou algum caracter especial no arquivo https://github.com/mixplick/nodejs-api/pull/1

**Comment by mixplick** [comment]
Muito obrigado pela ajuda.
